@startuml

'Documentation
'https://plantuml.com/activity-diagram-beta

'Online Editor
'http://www.plantuml.com/plantuml/dumla/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IW80

start
partition "Search for Solutions" {
    :Post Problem;
    fork
        repeat
            :Apply Tactic A;
        if (found elsewhere?) then ([stop])
            end
            note left: Flow Final Node
        endif
        repeat while (found?) is (no) not (yes)
        :Post Solution;
    fork again
       repeat
            :Apply Tactic B;
        if (found elsewhere?) then ([stop])
            end
        endif
        repeat while (found?) is (no) not (yes)
        :Post Solution;
    end fork
    :Select Solution;
    stop
}
@enduml